services:
  dev-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dev-db
  test-db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test-db
